name: Deploy Presigned Lambda

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  deploy-lambda-code:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1
      FUNCTION_NAME: hackathon_presigned_url

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar AWS credenciais via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Compactar Lambda em ZIP
        run: |
          cd presigned
          zip -r ../presigned.zip .
          cd ..

      - name: Atualizar código da Lambda existente
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.FUNCTION_NAME }} \
            --zip-file fileb://presigned.zip \
            --region ${{ env.AWS_REGION }}