name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy-lambda-code:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1
      PRESIGNED_URL_FUNCTION_NAME: hackathon_presigned_url
      EMAIL_NOTIFICATION_FUNCTION_NAME: hackathon_email_notification
      PROCESSOR_FUNCTION_NAME: hackathon_video_processor
      LISTING_FUNCTION_NAME: hackathon_listing_lambda

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar AWS credenciais via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Compactar Lambda de presigned
        run: |
          cd presigned
          zip -r ../presigned.zip lambda_function.py
          cd ..

      - name: Atualizar código da Lambda de presigned
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.PRESIGNED_URL_FUNCTION_NAME }} \
            --zip-file fileb://presigned.zip \
            --region ${{ env.AWS_REGION }}

      - name: Compacta Email Notification Lambda
        run: |
          cd notification
          zip -r ../email_notification.zip .
          cd ..

      - name: Atualizar código da Lambda Email Notification
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.EMAIL_NOTIFICATION_FUNCTION_NAME }} \
            --zip-file fileb://email_notification.zip \
            --region ${{ env.AWS_REGION }}

      - name: Compactar Lambda de Processamento
        run: |
          cd processor
          zip -r ../lambda_processor.zip .
          cd ..

      - name: Atualizar código da Lambda de Processamento
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.PROCESSOR_FUNCTION_NAME }} \
            --zip-file fileb://lambda_processor.zip \
            --region ${{ env.AWS_REGION }}

      - name: Compactar Lambda de listagem de Arquivos em ZIP
        run: |
          cd listing
          zip -r ../lambda_function.zip .
          cd ..

      - name: Atualizar código da Lambda de listagem
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LISTING_FUNCTION_NAME }} \
            --zip-file fileb://lambda_function.zip \
            --region ${{ env.AWS_REGION }}
