name: PR Quality Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  test-lambdas:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: us-east-1
      
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências de todas as lambdas
        run: |
          python -m pip install --upgrade pip
          for dir in presigned notification processor listing pre_sign_up; do
            if [ -f "$dir/requirements.txt" ]; then
              pip install -r "$dir/requirements.txt"
            fi
          done

      - name: Rodar testes com coverage
        run: |
          coverage run --source=presigned,notification,processor,listing -m pytest presigned notification processor listing pre_sign_up
          coverage report
          coverage xml

      - name: Rodar SonarCloud Scanner
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
