name: Test All Lambdas

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-lambdas:
    name: Rodar testes e cobertura com SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Rodar testes com cobertura por Lambda
        run: |
          rm -f .coverage  # limpa qualquer arquivo anterior
          for dir in presigned notification analytics; do
            echo "Processando Lambda em: $dir"
            cd "$dir"

            if [ -f requirements.txt ]; then
              echo "Instalando dependências..."
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            fi

            echo "Executando testes com coverage..."
            coverage run -m pytest || exit 1
            cd ..
          done

      - name: Combinar cobertura e gerar XML
        run: |
          coverage combine */.coverage
          coverage report
          coverage xml

      - name: Rodar SonarCloud Scanner
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
